### ISSUE TITLE
Error message when launching app on Mac OS X

### ISSUE THREAD

**Issue by alahj** [kimitzu/kimitzu-client#11]
**Describe the bug**
When I launch the Kimitzu app, I get the attached error. 
![Screen Shot 2019-12-21 at 7 27 17 AM](https://user-images.githubusercontent.com/53591309/71310026-00128f80-23c4-11ea-9ec9-eec8ff9d3924.png)

**To Reproduce**
1. Download installer
2. Install Kimitzu
3. Launch Kimitzu

**Expected behavior**
Launch without error.  

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS X (Mojave)
 - Version 0.1

**Comment by 24thsaint** [comment]
Seems like we had not added the prerelease configuration. Will update accordingly.

Note from docs:

```
allowPrerelease = false Boolean - GitHub provider only. Whether to allow update to pre-release versions. Defaults to true if application version contains prerelease components (e.g. 0.12.1-alpha.1, here alpha is a prerelease component), otherwise false.
```

**Comment by 24thsaint** [comment]
Fixed. Please redownload/reinstall the client to start receiving pre-release updates.
