### ISSUE TITLE
Some links on Kimitzu home page not working

### ISSUE THREAD

**Issue by alahj** [kimitzu/kimitzu-client#25]
**Describe the bug**
Buttons to "Demo" and "Github" on kimitzu.ch should be links to https://test.kimitzu.ch and https://github.com/kimitzu respectively.  However, neither appears to exist.  The link to the Releases (https://github.com/kimitzu/kimitzu-client/releases) fails with a 404 error, apparently due to a stray period.

**Comment by 24thsaint** [comment]
Fixed. https://github.com/kimitzu/kimitzu-landing/commit/1e3841f909273783ea48905569c8e8ace33a2c5b
