### ISSUE TITLE
When trying to pay, app hangs while "Requesting Merchant Address"

### ISSUE THREAD

**Issue by alahj** [kimitzu/kimitzu-client#38]
**Describe the bug**
I tried to purchase Jenny Cardeno's massage services.   However, when I tried to pay, I got a message that it was "Requesting Merchant Address"
**To Reproduce**
Try to purchase Jenny Cardeno's massage services.  When you click pay, you get the following screen, from which the app never returns.  

![Screen Shot 2020-01-08 at 4 23 36 AM](https://user-images.githubusercontent.com/53591309/71978148-80f8c600-31cf-11ea-8cfa-7953d2849d3d.png)

**Comment by alahj** [comment]
Still hanging.  I created a new listing withe Kimitzu-Client-0.3.1-beta.dmg.  Then tried to purchase it, and got the following screenshot.  Not sure if one can buy one's own listings, but if not it should give an error, rather than hang. 

![Screen Shot 2020-01-09 at 8 12 15 AM](https://user-images.githubusercontent.com/53591309/72084220-f50e9900-32b7-11ea-8ac8-af889a74f563.png)

**Comment by 24thsaint** [comment]
This unhandled error is fixed in v0.3.3, sir.

We plan to release every end of the week, Friday PHT. :))

**Comment by alahj** [comment]
Okay, thanks!

**Comment by alahj** [comment]
This is still behaving the same way in 0.3.3-beta.

**Comment by 24thsaint** [comment]
Have you tried the official v0.3.3-beta on the release section, sir? Does the issue still persist?

We may recommend you to clear the data folder on `$home/kimitzu` as it may possibly be a cache issue.

**Comment by alahj** [comment]
Yes, I upgraded to v0.3.3.-beta.  I'll try your suggestion.

**Comment by 24thsaint** [comment]
Error messages should show up now in case there are errors and not perpetually hang in "Requesting Merchant Address".
