### ISSUE TITLE
Upon launch app asks if I want to upgrade to v0.3.1-beta, even though I'm running v0.3.3-beta

### ISSUE THREAD

**Issue by alahj** [kimitzu/kimitzu-client#43]
**Describe the bug**
Upon launch app asks if I want to upgrade to v0.3.1-beta, even though I'm running v0.3.3-beta

**To Reproduce**
Download v0.3.3-beta.  Launch. 

**Expected behavior**
Should only ask to upgrade if running version is earlier than the latest version. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.0.1
 - Browser: Brave
 - Version: v0.3.3-beta
.

**Comment by 24thsaint** [comment]
Hmm... I believe this issue was opened before the official v0.3.3-beta was formally released?
