### ISSUE TITLE
Says " Connecting to Kimitzu, this might take a while..." forever

### ISSUE THREAD

**Issue by probonopd** [kimitzu/kimitzu-client#51]
**Describe the bug**

Says " Connecting to Kimitzu, this might take a while..." forever

**To Reproduce**

Launch the latest AppImage on Ubuntu 18.04.2 LTS (Bionic Beaver)

**Comment by 24thsaint** [comment]
Hello @probonopd !

Can you please try to run the AppImage on the terminal, wait a while, and forward a screenshot of it?

**Comment by probonopd** [comment]
```
me@host:~$ Downloads/Kimitzu-Client-0.4.0-beta.AppImage 
10:41:10.230 › Kimitzu Client v.0.4.0-beta is starting...
10:41:10.853 › Checking for update
10:41:11.133 › Openbazaar is starting
Spawning...  /tmp/.mount_KimitzTQ6GoM/resources/lib/openbazaard
10:41:11.146 › Openbazaar server is running.
10:41:11.199 › Server exited with code: 1.
10:41:12.492 › Update for version 0.4.0-beta is not available (latest version: 0.4.0-beta, downgrade is allowed).
10:41:12.492 › checkForUpdatesAndNotify called, downloadPromise is null
```

**Comment by 24thsaint** [comment]
Thank you for the information. It looks like OpenBazaar daemon failed to start.

We would like to investigate into it more, can you please attach the OB log file located on `$home/.kimitzu-ob/logs/ob.log`?

Thanks!

**Comment by probonopd** [comment]
`.kimitzu-ob` doesn't even exist... only `.config/kimitzu-client`

Does the AppImage not contain and launch the server component?

**Comment by 24thsaint** [comment]
The AppImage contains the server and launches it (there are two of them).

Somehow, yours is crashing on OpenBazaar. We'll have to try to run it on Ubuntu 18.04.2 and check if something is incompatible.

The latest AppImage (v0.4.0-beta) works well on our side, Ubuntu 19.04 Disco.

---

Meanwhile, would you like to try the [*.deb installer](https://github.com/kimitzu/kimitzu-client/releases/download/v0.4.0-beta/kimitzu-client_0.4.0-beta_amd64.deb) and check if the issue still persists?

**Comment by 24thsaint** [comment]
Environment replicated, confirmed not launching on 18.04.2.

---

Details:
`GLIBC_2.28 not found`. We compiled it with a higher version of GLIBC which is not present in Ubuntu 18.04... We'll either downgrade so that software will have backwards compatibility or compile Openbazaard statically.

**Comment by 24thsaint** [comment]
https://github.com/kimitzu/kimitzu-client/releases/tag/v0.4.0-beta

Fixed. Please download the client again. :))
Thank you for your interest in Kimitzu, welcome to the decentralized service marketplace!
