### ISSUE TITLE
Add ability to "Cancel" a sale. 

### ISSUE THREAD

**Issue by alahj** [kimitzu/kimitzu-client#72]
Right now, once a sale has been initiated, it appears to be impossible for seller to cancel the sale.  It should be possible to cancel a pending sale from the sales listing page. 

![Screenshot from 2020-01-21 21-34-06](https://user-images.githubusercontent.com/53591309/72868498-02079100-3c97-11ea-95ac-af9d3e11208a.png)

**Comment by 24thsaint** [comment]
`Offline orders` are the only purchases that can be cancelled by the buyer if it has not yet been confirmed by the vendor.

OB does not support cancelling `pending` orders outside of this context.
