### ISSUE TITLE
Stuck at Connecting to Kimitzu, this might take a while...

### ISSUE THREAD

**Issue by urbandroid** [kimitzu/kimitzu-client#89]
**Describe the bug**
Stuck at Connecting to Kimitzu, this might take a while...

**To Reproduce**
Just run it.

**Desktop (please complete the following information):**
$ snap version 
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  16.04
kernel  4.15.0-15-generic
kimitzu-client                   0.4.1-beta                   12     latest/beta    kimitzu 

**Additional context**
$ snap run kimitzu-client
09:20:36.303 › Kimitzu Client v.0.4.1-beta is starting...
09:20:36.546 › SNAP env is defined, updater is disabled
09:20:36.581 › Openbazaar is starting
Spawning...  /snap/kimitzu-client/12/resources/lib/openbazaard
09:20:36.599 › Openbazaar server is running.
09:20:36.686 › Server exited with code: 1.

Can be related to  #51

$ snap connections kimitzu-client 
Interface                 Plug                            Slot                             Notes
browser-support           kimitzu-client:browser-support  :browser-support                 -
content[gnome-3-28-1804]  kimitzu-client:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     kimitzu-client:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      kimitzu-client:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     kimitzu-client:sound-themes     gtk-common-themes:sound-themes   -
desktop                   kimitzu-client:desktop          :desktop                         -
desktop-legacy            kimitzu-client:desktop-legacy   :desktop-legacy                  -
gsettings                 kimitzu-client:gsettings        -                                -
home                      kimitzu-client:home             -                                -
network                   kimitzu-client:network          :network                         -
opengl                    kimitzu-client:opengl           :opengl                          -
pulseaudio                kimitzu-client:pulseaudio       -                                -
unity7                    kimitzu-client:unity7           :unity7                          -
wayland                   kimitzu-client:wayland          :wayland                         -
x11                       kimitzu-client:x11              :x11                             -

Log:

`[2021-01-06] [error] Error while reading user-preferences.json: Error: ENOENT: no such file or directory, open '/home/user/snap/kimitzu-client/12/.config/kimitzu-client/user-preferences.json'`

For security purposes no snap who connects to internet is allowed to access home, and they don't need it either, common directory in snaps own directory is enough to function properly (it lives and accessible even between version changes but deleted when snap uninstalled).  Files like "user-preferences.json" should be in common but if it should live even after snap uninstalled, personal files interface should be used, https://snapcraft.io/docs/personal-files-interface

**Comment by 24thsaint** [comment]
Hello @urbandroid, thank you for expressing your interest in Kimitzu.
This project has been discontinued and might be back in the near future. 🎉 

Happy new year.
